const ADMIN = "ADMIN";
const USER = "USER";
const ITEMCREATE = "ITEMCREATE";
const ITEMUPDATE = "ITEMUPDATE";
const ITEMDELETE = "ITEMDELETE";
const PERMISSIONUPDATE = "PERMISSIONUPDATE";

module.exports = {
	ADMIN,
	USER,
	ITEMCREATE,
	ITEMUPDATE,
	ITEMDELETE,
	PERMISSIONUPDATE,
};
